[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo  = 'ternjs/tern_for_vim'
build = 'npm install'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'scrooloose/syntastic.git'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'aharisu/vim_goshrepl'

[[plugins]]
repo = 'aharisu/vim-gdev'
