#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
setxkbmap -layout jp -option ctrl:nocaps

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
if type wicd-gtk >/dev/null 2>&1; then
    wicd-gtk -t &
fi
if type cbatticon >/dev/null 2>&1; then
    cbatticon &
fi
pcmanfm -d &
pasystray &
tilda &
fcitx &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
