#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
setxkbmap -layout jp -option ctrl:nocaps

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
# for Note PC
if type wicd-gtk >/dev/null 2>&1; then
    wicd-gtk -t &
fi
if type cbatticon >/dev/null 2>&1; then
    cbatticon &
fi
if type skypeforlinux > /dev/null 2>&1; then
    skypeforlinux &
fi

# for desktop
if xrandr | grep 2560x1440@55 > /dev/null; then
    xrandr --output HDMI1 --mode 2560x1440@55
fi

pcmanfm -d &
pasystray &
tilda &
fcitx &
gnome-screensaver &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
